---
- hosts: all
  tasks:
    - name: copy demoapp
      copy:
        src: /home/ubuntu/deploy/deploymentconfig/target
        dest: /home/ubuntu/deploy/deploymentconfig/

    - name: copy demoapp Dockerfile
      copy:
        src: /home/ubuntu/deploy/deploymentconfig/Dockerfile
        dest: /home/ubuntu/deploy/deploymentconfig/
    
    - name: copy demoapp docker-compose yml
      copy:
        src: /home/ubuntu/deploy/deploymentconfig/demoapp-docker-compose.yml
        dest: /home/ubuntu/deploy/deploymentconfig/
    
    - name: copy demoapp settings .env file
      copy:
        src: /home/ubuntu/deploy/deploymentconfig/demoapp.settings.qa.env
        dest: /home/ubuntu/deploy/deploymentconfig/
    
    - name: stop running demoapp container
      command: sudo docker container stop demoapp
      ignore_errors: True

    - name: remove existing demoapp container
      command: sudo docker container rm demoapp
      ignore_errors: True

    - name: remove existing demoapp image
      command: sudo docker rmi demoapp --force
      ignore_errors: True

    - name: remove existing webnet network
      command: sudo docker network rm webnet
      ignore_errors: True

    - name: create network webnet
      command: sudo docker network create webnet

    - name: build image of demoapp using the dockerfile in this path
      command: sudo docker image build -t demoapp /home/ubuntu/deploy/deploymentconfig

    - name: docker-compose-up demoapp
      command: sudo docker-compose --env-file /home/ubuntu/deploy/deploymentconfig/demoapp.settings.qa.env -f /home/ubuntu/deploy/deploymentconfig/demoapp-docker-compose.yml up -d